[project]
name = "chatpiano2024concertdanpart"
version = "0.1.0"
description = "Dan's part"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.30.0",
    "midi2audio>=0.1.1",
    "mido>=1.3.3",
    "requests>=2.32.3",
]
